/// Example application demonstrating UnionConfig usage.
/// Run with: dotnet run --project examples/ExampleApp
module ExampleApp.Program

open System
open System.IO
open UnionConfig.Types
open UnionConfig.Reader
open UnionConfig.EnvFile

// =============================================================================
// 1. Define config variables as a discriminated union
// =============================================================================

/// All configuration variables for the example app.
/// Using a DU means the compiler enforces exhaustive handling.
type AppConfig =
    | DatabaseUrl
    | DatabasePort
    | ApiKey
    | MaxRetries
    | DebugMode
    | LogLevel
    | FeatureNewUi

/// Map each DU case to its ConfigVarDef.
let configDef =
    function
    | DatabaseUrl ->
        { Name = "DATABASE_URL"
          Kind = Manual
          ValueType = StringType
          Requirement = Required
          IsSecret = false
          Doc =
            { Description = "PostgreSQL connection string"
              HowToFind = "Check your database provider dashboard"
              ManagementUrl = None } }
    | DatabasePort ->
        { Name = "DATABASE_PORT"
          Kind = AutoGenerated(Some "5432")
          ValueType = IntType
          Requirement = Optional
          IsSecret = false
          Doc =
            { Description = "Database port number"
              HowToFind = "Usually 5432 for PostgreSQL"
              ManagementUrl = None } }
    | ApiKey ->
        { Name = "API_KEY"
          Kind = Manual
          ValueType = StringType
          Requirement = Required
          IsSecret = true
          Doc =
            { Description = "External API key for third-party service"
              HowToFind = "Generate at https://dashboard.example.com/keys"
              ManagementUrl = Some(Uri "https://dashboard.example.com/keys") } }
    | MaxRetries ->
        { Name = "MAX_RETRIES"
          Kind = AutoGenerated(Some "3")
          ValueType = IntType
          Requirement = Optional
          IsSecret = false
          Doc =
            { Description = "Maximum retry attempts for failed requests"
              HowToFind = "Set to desired retry count (default: 3)"
              ManagementUrl = None } }
    | DebugMode ->
        { Name = "DEBUG_MODE"
          Kind = AutoGenerated(Some "false")
          ValueType = BoolType
          Requirement = Optional
          IsSecret = false
          Doc =
            { Description = "Enable debug logging"
              HowToFind = "Set to true or 1 to enable"
              ManagementUrl = None } }
    | LogLevel ->
        { Name = "LOG_LEVEL"
          Kind = Manual
          ValueType =
            CustomType(
                "LogLevel",
                fun s ->
                    match s.ToLowerInvariant() with
                    | "debug"
                    | "info"
                    | "warn"
                    | "error" -> None
                    | _ -> Some "must be debug, info, warn, or error"
            )
          Requirement = Optional
          IsSecret = false
          Doc =
            { Description = "Application log level"
              HowToFind = "One of: debug, info, warn, error"
              ManagementUrl = None } }
    | FeatureNewUi ->
        { Name = "FEATURE_NEW_UI"
          Kind = AutoGenerated(Some "false")
          ValueType = BoolType
          Requirement = Optional
          IsSecret = false
          Doc =
            { Description = "Feature flag: enable new UI"
              HowToFind = "Set to true to enable the redesigned UI"
              ManagementUrl = None } }

/// All config cases for iteration.
let allConfigs =
    [ DatabaseUrl
      DatabasePort
      ApiKey
      MaxRetries
      DebugMode
      LogLevel
      FeatureNewUi ]

/// All ConfigVarDefs.
let allDefs = allConfigs |> List.map configDef

// =============================================================================
// 2. Demonstrate reading config from environment
// =============================================================================

let demoReadFromEnv () =
    printfn "== Reading Config from Environment =="
    printfn ""

    // Set some env vars for the demo
    Environment.SetEnvironmentVariable("DATABASE_URL", "postgresql://localhost:5432/myapp")
    Environment.SetEnvironmentVariable("API_KEY", "sk-demo-key-abc123456")
    Environment.SetEnvironmentVariable("MAX_RETRIES", "5")
    Environment.SetEnvironmentVariable("DEBUG_MODE", "true")
    Environment.SetEnvironmentVariable("LOG_LEVEL", "info")
    Environment.SetEnvironmentVariable("FEATURE_NEW_UI", "1")

    // Read typed values
    let dbUrl = readString (configDef DatabaseUrl)
    let dbPort = readIntOrDefault (configDef DatabasePort) 5432
    let maxRetries = readIntOrDefault (configDef MaxRetries) 3
    let debug = readBoolOrDefault (configDef DebugMode) false
    let newUi = readBoolOrDefault (configDef FeatureNewUi) false

    printfn "  DATABASE_URL:    %s" dbUrl
    printfn "  DATABASE_PORT:   %d" dbPort
    printfn "  MAX_RETRIES:     %d" maxRetries
    printfn "  DEBUG_MODE:      %b" debug
    printfn "  FEATURE_NEW_UI:  %b" newUi

    // Pattern match on ConfigValue for full control
    match read (configDef LogLevel) with
    | Some(StringValue level) -> printfn "  LOG_LEVEL:       %s" level
    | _ -> printfn "  LOG_LEVEL:       (not set)"

    printfn ""

// =============================================================================
// 3. Demonstrate validation
// =============================================================================

let demoValidation () =
    printfn "== Validating Required Config =="
    printfn ""

    // With all vars set, validation passes
    let errors = validateRequired allDefs
    printfn "  Errors with all vars set: %d" errors.Length

    // Unset a required var and validate again
    Environment.SetEnvironmentVariable("DATABASE_URL", null)
    let errors2 = validateRequired allDefs
    printfn "  Errors with DATABASE_URL missing: %d" errors2.Length

    for err in errors2 do
        printfn "    - %s" err

    // Restore for remaining demos
    Environment.SetEnvironmentVariable("DATABASE_URL", "postgresql://localhost:5432/myapp")
    printfn ""

// =============================================================================
// 4. Demonstrate .env file operations
// =============================================================================

let demoEnvFile () =
    printfn "== .env File Operations =="
    printfn ""

    // Write a sample .env file
    let envPath = Path.Combine(Path.GetTempPath(), "unionconfig-example.env")

    let content =
        [ "# Example .env file"
          "DATABASE_URL=postgresql://localhost:5432/myapp"
          "DATABASE_PORT=5432"
          "API_KEY=sk-demo-key-abc123456"
          "MAX_RETRIES=3"
          "DEBUG_MODE=false"
          "LOG_LEVEL=info" ]
        |> String.concat "\n"

    File.WriteAllText(envPath, content)

    // Read it back
    let config = readEnvFile envPath
    printfn "  Read %d vars from %s" config.Count envPath

    for kvp in config do
        let display = maskValue kvp.Key kvp.Value
        printfn "    %s = %s" kvp.Key display

    printfn ""

    // Demonstrate config comparison (detecting drift)
    let staging = config

    let prod =
        staging
        |> Map.add "DATABASE_URL" "postgresql://prod-db.example.com:5432/myapp"
        |> Map.add "DEBUG_MODE" "false"
        |> Map.add "MAX_RETRIES" "5"
        |> Map.remove "LOG_LEVEL"

    let changes = compareConfigs staging prod
    printfn "  Comparing staging vs prod:"
    displayChanges changes

    // Clean up
    File.Delete(envPath)
    printfn ""

// =============================================================================
// 5. Demonstrate secret masking
// =============================================================================

let demoMasking () =
    printfn "== Secret Masking =="
    printfn ""

    let examples =
        [ ("DATABASE_URL", "postgresql://localhost:5432/myapp")
          ("API_KEY", "sk-demo-key-abc123456")
          ("JWT_SECRET", "super-long-secret-value-here")
          ("PASSWORD", "p@ss")
          ("DB_HOST", "localhost")
          ("PORT", "5432") ]

    for (key, value) in examples do
        let masked = maskValue key value
        printfn "  %-15s  %s" key masked

    printfn ""

// =============================================================================
// 6. Demonstrate ConfigValue extraction helpers
// =============================================================================

let demoConfigValueHelpers () =
    printfn "== ConfigValue Extraction Helpers =="
    printfn ""

    // These helpers provide a pipeline-friendly API
    let portValue = read (configDef MaxRetries) |> ConfigValue.intOption

    printfn "  MAX_RETRIES as intOption: %A" portValue

    let debugValue = read (configDef DebugMode) |> ConfigValue.boolOption
    printfn "  DEBUG_MODE as boolOption: %A" debugValue

    // Custom parser example
    let parseLogLevel (s: string) =
        match s.ToLowerInvariant() with
        | "debug" -> Some "DEBUG"
        | "info" -> Some "INFO"
        | "warn" -> Some "WARN"
        | "error" -> Some "ERROR"
        | _ -> None

    let level = read (configDef LogLevel) |> ConfigValue.customOption parseLogLevel
    printfn "  LOG_LEVEL as custom:      %A" level

    printfn ""

// =============================================================================
// 7. Demonstrate documentation metadata
// =============================================================================

let demoDocs () =
    printfn "== Config Variable Documentation =="
    printfn ""

    for config in allConfigs do
        let def = configDef config

        let kindStr =
            match def.Kind with
            | Manual -> "manual"
            | AutoGenerated(Some v) -> $"auto (default: %s{v})"
            | AutoGenerated None -> "auto"
            | Infrastructure -> "infra"
            | AutoProvisioned -> "provisioned"

        let reqStr =
            match def.Requirement with
            | Required -> "required"
            | Optional -> "optional"

        let secretStr = if def.IsSecret then " [SECRET]" else ""

        printfn "  %-20s %-10s %-12s%s" def.Name reqStr kindStr secretStr
        printfn "    %s" def.Doc.Description

        match def.Doc.ManagementUrl with
        | Some url -> printfn "    URL: %O" url
        | None -> ()

    printfn ""

// =============================================================================
// Run all demos
// =============================================================================

[<EntryPoint>]
let main _argv =
    printfn "UnionConfig Example App"
    printfn "======================"
    printfn ""

    demoReadFromEnv ()
    demoValidation ()
    demoEnvFile ()
    demoMasking ()
    demoConfigValueHelpers ()
    demoDocs ()

    printfn "Done!"
    0
