/// Reusable configuration types and utilities.
/// This module contains generic types for building type-safe configuration systems.
module UnionConfig.Types

open System

// =============================================================================
// Core Configuration Types (Reusable)
// =============================================================================

/// How a configuration variable gets its value
type ConfigVarKind =
    /// Must be explicitly provided by the user
    | Manual
    /// Auto-generated value with optional initial/default value
    | AutoGenerated of initialValue: string option
    /// Set automatically by CloudFormation/infrastructure (not editable in staging/prod)
    | Infrastructure
    /// Set automatically by a provisioning script (e.g., third-party service setup)
    | AutoProvisioned

/// The runtime type of a configuration variable's value
[<NoComparison; NoEquality>]
type ConfigValueType =
    /// String value (default)
    | StringType
    /// Integer value
    | IntType
    /// Boolean value (accepts true/false/1/0)
    | BoolType
    /// Float/double value
    | FloatType
    /// Custom type with validation function (typeName, validator that returns error message on failure)
    | CustomType of typeName: string * validate: (string -> string option)

/// Whether a configuration variable is required for the app to start
type ConfigRequirement =
    /// App will fail to start if this var is missing or empty
    | Required
    /// Var can be missing; read returns None
    | Optional

// =============================================================================
// Parsed Configuration Values
// =============================================================================

/// Parsed configuration value with its type
[<NoComparison; NoEquality>]
type ConfigValue =
    | StringValue of string
    | IntValue of int
    | BoolValue of bool
    | FloatValue of float

// =============================================================================
// Documentation Metadata
// =============================================================================

/// Documentation metadata for a config variable
[<NoComparison; NoEquality>]
type ConfigVarDoc =
    { Description: string
      HowToFind: string
      ManagementUrl: Uri option }

/// Core definition of a config variable (enough to read, parse, validate)
[<NoComparison; NoEquality>]
type ConfigVarDef =
    { Name: string
      Kind: ConfigVarKind
      ValueType: ConfigValueType
      Requirement: ConfigRequirement
      IsSecret: bool
      Doc: ConfigVarDoc }

// =============================================================================
// Parsing Utilities
// =============================================================================

/// Parse a string as a boolean value
/// Accepts: "true", "false", "1", "0" (case-insensitive, trimmed)
let parseBool (s: string) : bool option =
    match s.Trim().ToLowerInvariant() with
    | "true"
    | "1" -> Some true
    | "false"
    | "0" -> Some false
    | _ -> None

/// Parse a string value into the expected type.
let parseValue (valueType: ConfigValueType) (rawValue: string) : Result<ConfigValue, string> =
    match valueType with
    | StringType -> Ok(StringValue rawValue)
    | IntType ->
        match Int32.TryParse(rawValue) with
        | true, i -> Ok(IntValue i)
        | false, _ -> Error $"Expected integer, got '%s{rawValue}'"
    | BoolType ->
        match parseBool rawValue with
        | Some b -> Ok(BoolValue b)
        | None -> Error $"Expected true/false/1/0, got '%s{rawValue}'"
    | FloatType ->
        match Double.TryParse(rawValue) with
        | true, f -> Ok(FloatValue f)
        | false, _ -> Error $"Expected float, got '%s{rawValue}'"
    | CustomType(typeName, validate) ->
        match validate rawValue with
        | None -> Ok(StringValue rawValue) // Valid custom type, store as string
        | Some errorMsg -> Error $"Invalid %s{typeName}: %s{errorMsg}"

// =============================================================================
// ConfigValue Extraction Helpers
// =============================================================================

/// Helpers for extracting typed values from ConfigValue.
/// Use these with a `read` function that returns ConfigValue option:
///   let port = read PORT |> ConfigValue.int
///   let apiKey = read XAI_API_KEY |> ConfigValue.stringOption
module ConfigValue =
    /// Convert any ConfigValue to string representation
    let private valueToString =
        function
        | StringValue s -> s
        | IntValue i -> string<int> i
        | BoolValue b -> if b then "true" else "false"
        | FloatValue f -> string<float> f

    /// Extract string from Required config (converts any type to string)
    let string (cv: ConfigValue option) : string =
        match cv with
        | Some v -> valueToString v
        | None -> failwith "Configuration value is None for required var"

    /// Extract string from Optional config (converts any type to string)
    let stringOption (cv: ConfigValue option) : string option = cv |> Option.map valueToString

    /// Extract int from Required config
    let int (cv: ConfigValue option) : int =
        match cv with
        | Some(IntValue i) -> i
        | Some(StringValue s) ->
            match Int32.TryParse(s) with
            | true, i -> i
            | false, _ -> failwithf "Cannot convert '%s' to int" s
        | Some _ -> failwith "Type mismatch: expected int"
        | None -> failwith "Configuration value is None for required var"

    /// Extract int from Optional config
    let intOption (cv: ConfigValue option) : int option =
        match cv with
        | Some(IntValue i) -> Some i
        | Some(StringValue s) ->
            match Int32.TryParse(s) with
            | true, i -> Some i
            | false, _ -> failwithf "Cannot convert '%s' to int" s
        | Some _ -> failwith "Type mismatch: expected int"
        | None -> None

    /// Extract bool from Required config
    let bool (cv: ConfigValue option) : bool =
        match cv with
        | Some(BoolValue b) -> b
        | Some _ -> failwith "Type mismatch: expected bool"
        | None -> failwith "Configuration value is None for required var"

    /// Extract bool from Optional config
    let boolOption (cv: ConfigValue option) : bool option =
        match cv with
        | Some(BoolValue b) -> Some b
        | Some _ -> failwith "Type mismatch: expected bool"
        | None -> None

    /// Extract float from Required config
    let float (cv: ConfigValue option) : float =
        match cv with
        | Some(FloatValue f) -> f
        | Some(StringValue s) ->
            match Double.TryParse(s) with
            | true, f -> f
            | false, _ -> failwithf "Cannot convert '%s' to float" s
        | Some _ -> failwith "Type mismatch: expected float"
        | None -> failwith "Configuration value is None for required var"

    /// Extract float from Optional config
    let floatOption (cv: ConfigValue option) : float option =
        match cv with
        | Some(FloatValue f) -> Some f
        | Some(StringValue s) ->
            match Double.TryParse(s) with
            | true, f -> Some f
            | false, _ -> failwithf "Cannot convert '%s' to float" s
        | Some _ -> failwith "Type mismatch: expected float"
        | None -> None

    /// Parse custom type from Required config using provided parser
    let custom<'T> (parser: string -> 'T option) (cv: ConfigValue option) : 'T =
        match cv with
        | Some v ->
            let s = valueToString v

            match parser s with
            | Some parsed -> parsed
            | None -> failwithf "Failed to parse custom type from '%s'" s
        | None -> failwith "Configuration value is None for required var"

    /// Parse custom type from Optional config using provided parser
    let customOption<'T> (parser: string -> 'T option) (cv: ConfigValue option) : 'T option =
        match cv with
        | Some v ->
            let s = valueToString v

            match parser s with
            | Some parsed -> Some parsed
            | None -> failwithf "Failed to parse custom type from '%s'" s
        | None -> None
